services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2378:2379"
    volumes:
      - etcd_data:/etcd_data

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data --address ":9001"
    ports:
      - "9002:9001"
    volumes:
      - minio_data:/data

  milvus:
    image: milvusdb/milvus:v2.4.8
    command: [ "milvus", "run", "standalone" ]
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9001
    ports:
      - "19531:19530"
     
    depends_on:
      - etcd
      - minio
    volumes:
      - milvus_data:/var/lib/milvus

  attu:
    image: zilliz/attu:v2.4.12          # 官方最新镜像
    container_name: rag_attu
    ports:
      - "8011:3000"                   # 浏览器访问端口
    environment:
      - MILVUS_URL=milvus:19530       # 容器内服务名即可
      - HOST_URL=http://192.168.242.193:8011 # 前端回调地址
    depends_on:
      - milvus

  app:  
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rag_app
    ports:
      - "8010:8010"
    depends_on:
      - milvus
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - HF_ENDPOINT=https://hf-mirror.com
      - USE_RERANKER=true
      - RERANKER_TOP_K=5
      - INITIAL_RETRIEVAL_TOP_K=10
      - EMBEDDING_GPU_DEVICES=cpu
      - RERANKER_GPU_DEVICES=cuda:1
      - ENABLE_MEMORY_OPTIMIZATION=true
      - MAX_MEMORY_FRACTION=0.8
      - ENABLE_MEMORY_POOLING=true
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    volumes:
      - ./app/models:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # 只使用1个GPU
              capabilities: [gpu]
        limits:
          memory: 8G  # 减少内存分配

volumes:
  etcd_data:
  minio_data:
  milvus_data: